### ISSUE TITLE
README is out of date and can use some linting

### ISSUE THREAD

**Issue by izilla** [quantfive/react-slide-menu#1]
I can create a PR for the changes I think should be necessary. Currently the directions in the README do not reflect the actual options for the component. I tried creating a PR but am getting a `403`.

Let me know if there is anything else I can do to help 👍

**Comment by lightninglu10** [comment]
@izilla did you follow these steps for a PR? Would love one if the README is out of date: https://stackoverflow.com/posts/29044573/revisions

**Comment by izilla** [comment]
OK new here I go:

https://github.com/quantfive/react-slide-menu/pull/5

**Comment by izilla** [comment]
@lightninglu10 thank you for that tip, I usually am a contributor on my PRs 💪

**Comment by lightninglu10** [comment]
Got this merged in, thanks for the PR @izilla
